### ISSUE TITLE
Using apcupsd/NUT_tools backend for genpowerd.

### ISSUE THREAD

**Issue by ghost** [quinot/genpower#1]
Feature request:

ATM, genpowerd is a standard UPS daemon for UNIX. However, many and many UPSes do not use serial line connections any more. There are other daemons dedicated to providing USP support.

Could I ask for a feature to be added: to use apcupsd or/and Network UPS Tools as a back-end for genpowerd?

It would allow to introduce support to many more devices available on the market.

**Comment by quinot** [comment]
There would be little point for such a backend. Nut provides all of the functionality of genpowerd, and then more.
